// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.10
// source: strelka.proto

package strelka

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FrontendClient is the client API for Frontend service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FrontendClient interface {
	ScanFile(ctx context.Context, opts ...grpc.CallOption) (Frontend_ScanFileClient, error)
}

type frontendClient struct {
	cc grpc.ClientConnInterface
}

func NewFrontendClient(cc grpc.ClientConnInterface) FrontendClient {
	return &frontendClient{cc}
}

func (c *frontendClient) ScanFile(ctx context.Context, opts ...grpc.CallOption) (Frontend_ScanFileClient, error) {
	stream, err := c.cc.NewStream(ctx, &Frontend_ServiceDesc.Streams[0], "/Frontend/ScanFile", opts...)
	if err != nil {
		return nil, err
	}
	x := &frontendScanFileClient{stream}
	return x, nil
}

type Frontend_ScanFileClient interface {
	Send(*ScanFileRequest) error
	Recv() (*ScanResponse, error)
	grpc.ClientStream
}

type frontendScanFileClient struct {
	grpc.ClientStream
}

func (x *frontendScanFileClient) Send(m *ScanFileRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *frontendScanFileClient) Recv() (*ScanResponse, error) {
	m := new(ScanResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FrontendServer is the server API for Frontend service.
// All implementations should embed UnimplementedFrontendServer
// for forward compatibility
type FrontendServer interface {
	ScanFile(Frontend_ScanFileServer) error
}

// UnimplementedFrontendServer should be embedded to have forward compatible implementations.
type UnimplementedFrontendServer struct {
}

func (UnimplementedFrontendServer) ScanFile(Frontend_ScanFileServer) error {
	return status.Errorf(codes.Unimplemented, "method ScanFile not implemented")
}

// UnsafeFrontendServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FrontendServer will
// result in compilation errors.
type UnsafeFrontendServer interface {
	mustEmbedUnimplementedFrontendServer()
}

func RegisterFrontendServer(s grpc.ServiceRegistrar, srv FrontendServer) {
	s.RegisterService(&Frontend_ServiceDesc, srv)
}

func _Frontend_ScanFile_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FrontendServer).ScanFile(&frontendScanFileServer{stream})
}

type Frontend_ScanFileServer interface {
	Send(*ScanResponse) error
	Recv() (*ScanFileRequest, error)
	grpc.ServerStream
}

type frontendScanFileServer struct {
	grpc.ServerStream
}

func (x *frontendScanFileServer) Send(m *ScanResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *frontendScanFileServer) Recv() (*ScanFileRequest, error) {
	m := new(ScanFileRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Frontend_ServiceDesc is the grpc.ServiceDesc for Frontend service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Frontend_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Frontend",
	HandlerType: (*FrontendServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ScanFile",
			Handler:       _Frontend_ScanFile_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "strelka.proto",
}
