---
repos:
  - repo: https://github.com/psf/black
    rev: "22.6.0"
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
#      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args:
          - -b main
  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: "5.11.5"
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.961
#    hooks:
#      - id: mypy
#        additional_dependencies:
#          - types-requests
