# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import strelka_pb2 as strelka__pb2


class StrelkaStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.StreamData = channel.stream_unary(
        '/Strelka/StreamData',
        request_serializer=strelka__pb2.ScanData.SerializeToString,
        response_deserializer=strelka__pb2.ScanResult.FromString,
        )
    self.SendLocation = channel.unary_unary(
        '/Strelka/SendLocation',
        request_serializer=strelka__pb2.ScanLocation.SerializeToString,
        response_deserializer=strelka__pb2.ScanResult.FromString,
        )


class StrelkaServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def StreamData(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendLocation(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StrelkaServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'StreamData': grpc.stream_unary_rpc_method_handler(
          servicer.StreamData,
          request_deserializer=strelka__pb2.ScanData.FromString,
          response_serializer=strelka__pb2.ScanResult.SerializeToString,
      ),
      'SendLocation': grpc.unary_unary_rpc_method_handler(
          servicer.SendLocation,
          request_deserializer=strelka__pb2.ScanLocation.FromString,
          response_serializer=strelka__pb2.ScanResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Strelka', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
