# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: strelka/proto/mmbot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='strelka/proto/mmbot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x19strelka/proto/mmbot.proto\"\x12\n\x03Vba\x12\x0b\n\x03vba\x18\x01 \x01(\t\" \n\nPrediction\x12\x12\n\nprediction\x18\x01 \x01(\t2\'\n\x05Mmbot\x12\x1e\n\x07SendVba\x12\x04.Vba\x1a\x0b.Prediction\"\x00\x62\x06proto3')
)




_VBA = _descriptor.Descriptor(
  name='Vba',
  full_name='Vba',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='vba', full_name='Vba.vba', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=47,
)


_PREDICTION = _descriptor.Descriptor(
  name='Prediction',
  full_name='Prediction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prediction', full_name='Prediction.prediction', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=81,
)

DESCRIPTOR.message_types_by_name['Vba'] = _VBA
DESCRIPTOR.message_types_by_name['Prediction'] = _PREDICTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vba = _reflection.GeneratedProtocolMessageType('Vba', (_message.Message,), dict(
  DESCRIPTOR = _VBA,
  __module__ = 'strelka.proto.mmbot_pb2'
  # @@protoc_insertion_point(class_scope:Vba)
  ))
_sym_db.RegisterMessage(Vba)

Prediction = _reflection.GeneratedProtocolMessageType('Prediction', (_message.Message,), dict(
  DESCRIPTOR = _PREDICTION,
  __module__ = 'strelka.proto.mmbot_pb2'
  # @@protoc_insertion_point(class_scope:Prediction)
  ))
_sym_db.RegisterMessage(Prediction)



_MMBOT = _descriptor.ServiceDescriptor(
  name='Mmbot',
  full_name='Mmbot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=83,
  serialized_end=122,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendVba',
    full_name='Mmbot.SendVba',
    index=0,
    containing_service=None,
    input_type=_VBA,
    output_type=_PREDICTION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MMBOT)

DESCRIPTOR.services_by_name['Mmbot'] = _MMBOT

# @@protoc_insertion_point(module_scope)
