# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mmbot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bmmbot.proto\"\x12\n\x03Vba\x12\x0b\n\x03vba\x18\x01 \x01(\t\" \n\nPrediction\x12\x12\n\nprediction\x18\x01 \x01(\t2\'\n\x05Mmbot\x12\x1e\n\x07SendVba\x12\x04.Vba\x1a\x0b.Prediction\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mmbot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _VBA._serialized_start=15
  _VBA._serialized_end=33
  _PREDICTION._serialized_start=35
  _PREDICTION._serialized_end=67
  _MMBOT._serialized_start=69
  _MMBOT._serialized_end=108
# @@protoc_insertion_point(module_scope)
