name: Build and Attach Go Binaries to Release

on:
  push:
    branches:
      - test-go-binary0build

permissions:
  contents: write

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Action Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build and Upload Windows x64 Binary
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags="-s -w" -o strelka-fileshot-win.exe src/go/cmd/strelka-fileshot/main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=asset_path::strelka-fileshot-win.exe"
          echo "::set-output name=asset_name::strelka-fileshot-win.exe"

      - name: Upload Windows x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://github.com/upload/releases/108463777"
          asset_path: ${{ needs.build_and_upload.outputs.asset_path }}
          asset_name: ${{ needs.build_and_upload.outputs.asset_name }}
          asset_content_type: application/octet-stream

      - name: Build and Upload Linux x64 Binary
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o strelka-fileshot-linux src/go/cmd/strelka-fileshot/main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=asset_path::strelka-fileshot-linux"
          echo "::set-output name=asset_name::strelka-fileshot-linux"

      - name: Upload Linux x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://github.com/upload/releases/108463777"
          asset_path: ${{ needs.build_and_upload.outputs.asset_path }}
          asset_name: ${{ needs.build_and_upload.outputs.asset_name }}
          asset_content_type: application/octet-stream

      - name: Build and Upload Mac x64 Binary
        run: |
          GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o strelka-fileshot-mac64 src/go/cmd/strelka-fileshot/main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=asset_path::strelka-fileshot-mac64"
          echo "::set-output name=asset_name::strelka-fileshot-mac64"

      - name: Upload Mac x64 Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://github.com/upload/releases/108463777"
          asset_path: ${{ needs.build_and_upload.outputs.asset_path }}
          asset_name: ${{ needs.build_and_upload.outputs.asset_name }}
          asset_content_type: application/octet-stream

      - name: Build and Upload Mac ARM Binary
        run: |
          GOOS=darwin GOARCH=arm64 go build -ldflags="-s -w" -o strelka-fileshot-macarm src/go/cmd/strelka-fileshot/main.go
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=asset_path::strelka-fileshot-macarm"
          echo "::set-output name=asset_name::strelka-fileshot-macarm"

      - name: Upload Mac ARM Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://github.com/upload/releases/108463777"
          asset_path: ${{ needs.build_and_upload.outputs.asset_path }}
          asset_name: ${{ needs.build_and_upload.outputs.asset_name }}
          asset_content_type: application/octet-stream
